export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAIL = 'POST_FAIL';

export const POST_ONE_REQUEST = 'POST_ONE_REQUEST';
export const POST_ONE_SUCCESS = 'POST_ONE_SUCCESS';
export const POST_ONE_FAIL = 'POST_ONE_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';